/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess.clientserver.example;

import com.fasterxml.jackson.core.type.TypeReference;
import edu.austral.ingsis.clientserver.Message;
import edu.austral.ingsis.clientserver.netty.client.NettyClientBuilder;
import edu.austral.ingsis.clientserver.netty.server.NettyServerBuilder;

import java.net.InetSocketAddress;

public class ServerExample {

    public static void main(String[] args) {
        final var server = NettyServerBuilder.Companion.createDefault()
                .withPort(8095)
                .withConnectionListener(new MyServerConnectionListener())
                .addMessageListener("hello", new TypeReference<>() {
                }, new HelloListener())
                .build();

        server.start();

        try {
            while (true) {
                Thread.sleep(1000);
                server.broadcast(new Message<>("ping", "Are you there?"));
            }
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
