/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess.clientserver.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ClientExample classUnderTest = new ClientExample();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
